### ISSUE TITLE
rubygems.org

### ISSUE THREAD

**Issue by comicmuse** [hihouhou/huginn_influxdb_write_data_agent#1]
Bonjour,

Have you considered publishing your huginn agents to rubygems.org?

**Comment by hihouhou** [comment]
Hello,
no :-)

**Comment by hihouhou** [comment]
any problems with huginn config file for integrating it ?

**Comment by comicmuse** [comment]
Only that I didn't realise I could use ADDITIONAL_GEMS from github in the docker installation. I've done this now and it's working great. Thanks
