### ISSUE TITLE
ERROR:  Could not find a valid gem 'huginn_influxdb_write_data_agent' (>= 0) in any repository ERROR:  Possible alternatives: huginn_sqlite3_agent, huginn_sqlite_agent

### ISSUE THREAD

**Issue by upuldi** [hihouhou/huginn_influxdb_write_data_agent#3]
I am trying to get it installed in the huginn docker, I logged into the docker and tried the following command, However getting the below error.

`
   
    default@f5cdb452b4f7:~$ gem install huginn_influxdb_write_data_agent
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    ERROR:  Could not find a valid gem 'huginn_influxdb_write_data_agent' (>= 0) in any repository
    ERROR:  Possible alternatives: huginn_sqlite3_agent, huginn_sqlite_agent
`

**Comment by hihouhou** [comment]
Hello, for installing this gem , you need to use the .env file like ADDITIONAL_GEMS=huginn_influxdb_write_data_agent(github: hihouhou/huginn_influxdb_write_data_agent , the version  ADDITIONAL_GEMS=huginn_influxdb_write_data_agent should works but I never tested :-) could you try like I did ?

**Comment by hihouhou** [comment]
no news , good news -> closed
